services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: autoflex-oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=autoflex_pwd
      - APP_USER=inventory_user
      - APP_USER_PASSWORD=inventory_pwd
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exit | sqlplus -L -S / AS SYSDBA @?/rdbms/admin/sqlsess.sql",
        ]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 60s
    networks:
      - inventory-net
    volumes:
      - oracle_data:/opt/oracle/oradata

  backend:
    build: ./backend-quarkus
    container_name: autoflex-backend
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - QUARKUS_HTTP_CORS_ORIGINS=http://localhost,http://127.0.0.1
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - QUARKUS_DATASOURCE_USERNAME=inventory_user
      - QUARKUS_DATASOURCE_PASSWORD=inventory_pwd
      - QUARKUS_HTTP_HOST=0.0.0.0
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - inventory-net

  frontend:
    build:
      context: ./frontend-react
      args:
        - VITE_API_URL=http://localhost:8081/api
    container_name: autoflex-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - inventory-net

networks:
  inventory-net:
    driver: bridge

volumes:
  oracle_data:
